spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/coupon?serverTimezone=+09:00
    username: root
    password: ${LOCAL_DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.r2dbc.core: debug