spring:
  r2dbc:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  data:
    redis:
      host:
      port:

logging:
  level:
    org.springframework.r2dbc.core: debug