name: publish to ghcr.io

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./prod.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mujinjang:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
